CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role INT NOT NULL,
  last_edited TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (role) REFERENCES roles(id)
);

INSERT INTO roles (name) VALUES ('admin'), ('user') ON DUPLICATE KEY UPDATE name=name;

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    username VARCHAR(255) NOT NULL,
    expires_at INT NOT NULL
);

CREATE TABLE IF NOT EXISTS config_int (
  key VARCHAR(50) NOT NULL UNIQUE,
  value INT NOT NULL DEFAULT(0)
)




